apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Lykke.Service.PushNotifications
  labels:
    app: push-notifications
    environment: Development
    tier: Service
  name: push-notifications
  namespace: services
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: push-notifications
  template:
    metadata:
      labels:
        app: push-notifications
      name: push-notifications
    spec:
 #     nodeSelector:
 #       type: 
 #     tolerations:
 #     - effect: NoSchedule
 #       operator: Exists
      imagePullSecrets:
      - name: push-notifications-docker
      containers:
      - name: push-notifications
        image: lykkebusiness/service-pushnotifications:dev
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 128Mi 
            cpu: 40m 
          limits:
            memory: 1024Mi 
            cpu: 1000m 
        env:
        - name: BuildNumber
          value: '$version'
        - name: SettingsUrl
          value: '$ConnectionString'
        - name: ENV_INFO
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: 
        - name: MyMonitoringUrl
          value: http://push-notifications.services.svc.cluster.local/api/isalive
        - name: EncryptionKey
          valueFrom:
            secretKeyRef:
              name: push-notifications
              key: EncryptionKey
        - name: EncryptionIV
          valueFrom:
            secretKeyRef:
              name: push-notifications
              key: EncryptionIV
